#!/usr/bin/env python3

import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)
    
def join_canal(canal, connec):
    aux = canal
    canal = canal.lower()
    if canal not in servidor.canais:
        servidor.canais[canal] = []
    if connec not in servidor.canais[canal]:
        servidor.canais[canal].append(connec)
 #incompleto

def enviamsg (de, para, msg):
    if para[0] == 35:
        if para.lower() in servidor.canais:
            for i in servidor.canais[para.lower()]:
                if i.nickname != de:
                    i.enviar(b' :%s PRIVMSG %s :%s\r\n' % (de, para, msg))
    else if
    # incompleto


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
servidor.canais = {}
servidor.nicknames = {}
